In [1]:
import numpy as np


In [3]:
import numpy as np
# Create a numpy array
arr = np.array([1, 2, 3, 4, 5])

# Calculate the mean of the array
mean = np.mean(arr)
# Output: Mean: 3.0
print("Mean:", mean)

# Calculate the median of the array
median = np.median(arr)
# Output: Median: 3.0
print("Median:", median)

# Calculate the standard deviation of the array
std_dev = np.std(arr)
# Output: Standard Deviation: 1.4142135623730951
print("Standard Deviation:", std_dev)

# Calculate the variance of the array
variance = np.var(arr)
# Output: Variance: 2.0
print("Variance:", variance)

# Calculate the maximum value of the array
max_val = np.max(arr)
# Output: Maximum Value: 5
print("Maximum Value:", max_val)

# Calculate the minimum value of the array
min_val = np.min(arr)
# Output: Minimum Value: 1
print("Minimum Value:", min_val)


一维数组： [1 2 3 4 5]
二维数组：
 [[1 2 3]
 [4 5 6]]
全零二维数组：
 [[0. 0. 0.]
 [0. 0. 0.]]
全一二维数组：
 [[1. 1. 1.]
 [1. 1. 1.]]
单位矩阵：
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
arr2的形状： (2, 3)
arr2的维度： 2
arr2元素总数： 6
改变形状后的数组：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
数组加法：
 [ 2  4  6  8 10]
数组乘法：
 [ 1  4  9 16 25]


In [ ]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Slice the array to get elements from index 2 to index 6 (exclusive)
slice1 = arr[2:6]
print("Slice 1:", slice1)
# Output: Slice 1: [3 4 5 6]

# Slice the array to get every second element starting from index 1
slice2 = arr[1::2]
print("Slice 2:", slice2)
# Output: Slice 2: [2 4 6 8 10]

# Slice the array to get elements from index 3 to the end
slice3 = arr[3:]
print("Slice 3:", slice3)
# Output: Slice 3: [4 5 6 7 8 9 10]

# Slice the array to get elements from the beginning to index 5 (exclusive)
slice4 = arr[:5]
print("Slice 4:", slice4)
# Output: Slice 4: [1 2 3 4 5]

# Slice the array to get elements from index -3 to index -1
slice5 = arr[-3:-1]
print("Slice 5:", slice5)
# Output: Slice 5: [8 9]
